### PR TITLE
mnater/Hyphenator#275 guarding fullPath (undefined in IE 11)

### PR DESCRIPTION
**Pull request by rreitmann**
Sorry, my previous fix was incomplete.

### CODE REVIEW

**Comment by mnater** [comment]
Thanks again;-)

**Comment by rreitmann** [comment]
Your welcome, when will you release this? Asking because I want to eliminate the "master"-dependency in our bower.json.

**Comment by mnater** [comment]
Not very soon, sorry.
I'm quite busy at the time and I like to set up a test for your case, first (I just blindly merged your commits, because they look fine to me, haven't tested yet).
Give me a month…

**Comment by rreitmann** [comment]
Ok, please drop me a note when you have released.

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenator/releases/tag/5.2.1

**Comment by rreitmann** [comment]
Thanks, but the release tag is not available anymore...

**Comment by mnater** [comment]
sorry, needed to delete that.
https://github.com/mnater/Hyphenator/releases/tag/5.3.0

**Pull request merged**
